mystor/git-revise

zipfix/__init__.py

Which automatically stages all the changes the same way `git commit -a` would,
without staging untracked files.

Introduce git zipfix -a.

---

gitrevise/utils.py

The subshell `$(...)` inside `exec` inside `bash -c` will not work when
`GIT_EDITOR` contains quoted arguments. For example:
$ GIT_EDITOR='vim -u "myvimrc"' git revise -i
E282: Cannot read from ""myvimrc""
Note the double quoting in the error message. So the quotes around the
filename were considered literal.
If you need some white spaces inside the quoted part, things get
weirder:
$ GIT_EDITOR='vim -u "myvim rc"' git revise -i
2 files to edit
E282: Cannot read from ""myvim"
Now `"myvim` and `rc"` are considered two different arguments.
The proposed change removes the subshell in favor of getting the
GIT_EDITOR contents in a separate step. That way, all the quoting and
spacing work as expected.
Fixes #30

Add support for GIT_EDITOR containing quotes

---

gitrevise/odb.py
gitrevise/utils.py

This branch makes sure git revise uses the core.commentchar config in the editor, and this fixes #22.
It uses the comment char as set in the config, defaults to `#` if not present, and picks the comment char from a set of options when `auto` is set, just as git does (failing with the same message when no suitable char is found).
I'm no Python programmer, and thus not aware of idiomatic Python usage. Feel free to comment on that. Furthermore, I hope I got the `bytes` vs `str` correct.

Add support for git config core.commentchar

---

docs/conf.py
docs/man.rst
git-revise.1
gitrevise/odb.py
gitrevise/tui.py
tests/test_interactive.py

This PR builds on top of my other PR (#38 support core.commentchar) which introduced the `repo.config` function. Hence the commentchar things in the diffs.
Just like my other pull request, I'm quite new to python, its ecosystem and best practices, so I'm happy to learn from your feedback.
Some observations/questions from my side:
I noticed that git-revise.1 (the compiled man page) is in git, but is outdated.
Should this file be in git? If yes, should I commit it as well?
Now you can call `git revise -i --autosquash --no-autosquash`. This behaves the same as `git revise -i --autosquash --no-autosquash`, in that it does _not_ autosquash. The options can be made mutually exclusive, but since `git rebase` accepts them, I tend to leave it like it is.
I'm not really happy with the unit tests, …

Support revise.autosquash

---

MANIFEST.in

"A copy of the license and copyright notice must be included with the software."

Include license in PyPI package

---

gitrevise/utils.py

Mostly for editors where trailing whitespace is always highlighted.

Do not generate trailing whitespaces when writing comments

---

docs/man.rst
git-revise.1
gitrevise/todo.py

Deleted lines are no longer treated as index commands. Mention that
the number of lines must remain identical and that index commands must
come last. Adapt 'fixup' and 'squash' to mirror 'git rebase', so that
the 'fixup' help in the todo list mentions that the message is dropped.
Misc rephrasing.

Update documentation of to-do list index command

---

setup.py

The Filesystem Hierarchy Standard wants man pages installed inside share/man, not man.

Update man page install path to follow FSH

---

gitrevise/todo.py
tests/test_fixup.py

Fixup commits usually use subject line of the target commit. But it is
also possible to specify the target commit's hash directly (or some
prefix of it):
fixup! faab8b162
This was added in Git in
https://github.com/git/git/commit/68d5d03bc49a073be3b0e14b22d30d70e7ae686d
and currently supported here:
https://github.com/git/git/blob/c44a4c650c66eb7b8d50c57fd4e1bff1add7bf77/sequencer.c#L2853-L2859

Support fixups with explicit hashes

---

gitrevise/todo.py
gitrevise/utils.py

When editing the `revise-todo`, `git-revise` now determines the editor to use with the same logic as `git-rebase-interactive` (see [`git/editor.c`](https://github.com/git/git/blob/b34789c0b0d3b137f0bb516b417bd8d75e0cb306/editor.c#L17-L48)'s `git_editor` v. `git_sequence_editor`).
This is useful if you have a custom sequence editor configured which is different than the normal commit message editor.

Respect `SEQUENCE_EDITOR` and `sequence.editor` vars

---

README.md

Update the readme to show that there is now a Fedora git-revise package that can be installed.

Add Fedora install instructions to readme

---

gitrevise/merge.py
gitrevise/todo.py
gitrevise/tui.py
gitrevise/utils.py
tests/test_fixup.py

When adding a new fixup to commit X, we want to add it after all previous
fixup commits that target X, and after fixups to those commits, and so on.
The cycle detection might be a bit over-the-top, since the logic only allows
to create self cycles with a message like `fixup! fixup!`.
If we only allowed to fixup previous commits in the todo list, then there would
not be cycles by design, that could simplify this patch.
Fixes #69

Fix order of fixup commits with autosquash

---

gitrevise/todo.py
gitrevise/tui.py
tests/test_fixup.py

This eliminates the need to check for a cycle in the fixup graph, see
5f4639a Fix order of fixup commits with autosquash (#72).
---
I guess `visited` could stay with a hard fail instead of looping when there is a cycle, but that is impossible at the moment.

Rule out fixup cycles by building autosquash todo list step by step

---

docs/performance.rst
gitrevise/merge.py
gitrevise/odb.py
tests/test_rerere.py

This adds basic support for [git-rerere].
Whenever a merge conflict in a file is successfully resolved by the user,
the conflict (the preimage) and the merged file (the postimage) are recorded.
When resolving the same conflict again, the recorded resolution is replayed,
unless it doesn't merge cleanly with the current preimage.
The resolutions are shared with the ones that git-rerere records;
both save them in .git/rr-cache/<conflict-id>.
My motivation is that I'm using git-revise in a script that sometimes needs
to resolve the same conflicts over and over again. By caching conflict
resolutions I only need to do that once.
This feature is disabled by default.  Use it by enabling revise.rerere (or
rerere.enabled) _and_ rerere.autoUpdate. In future, we plan to also support
use without …

Support git-rerere to record and replay conflict resolution

---

gitrevise/merge.py
tests/test_rerere.py

Prior to this change, we only used recorded resolutions if
"rerere.autoUpdate" was true. Also use them if it's false, but only
if the user confirms.
In future, we can allow editing conflict resolutions.

Prompt to use recorded resolution when rerere.autoupdate is disabled

---

CHANGELOG.md
gitrevise/odb.py
tests/test_fixup.py

A Git commit summary (also called "subject") includes all lines before
the first blank line in the commit message.
When creating a fixup commit for a commit X, Git joins all lines in
the summary of X, so the "fixup! Summary of X" message will always
be a single line.
The same thing happens when building a rebase-todo list. Joining the
subject into one line makes sure that multiline summaries don't create
invalid todo lists.
Always squash the summary into one line, since we use it only in
contexts where a single line is desired.

Support multiline commit summaries

---

gitrevise/todo.py

This matches the git-rebase behavior
---------------
Inserting an extra space in the todo-list no longer fails with `invalid value: todo entry 'r <EXTRA SPACE> <HASH> ...'`

Allow more spaces after the command keyword

---

gitrevise/odb.py

This currently makes the Python 3.9 linter fail
We could also disable it globally, but it might be useful?

Disable false positive Pylint warning

---

gitrevise/merge.py

The `labels` tuple contains `(current, base, other)`, and the prompt is choosing between `current` and `other`.
Previously, the prompt would erroneously use the `base` label for the `other` value.

merge.conflict_prompt: Fix incorrect prompt label

---

gitrevise/merge.py

When two entries are both files but have conflicting permissions (`755` vs `644`), previously `git-revise` would default to `755`. Instead, this now prompts the user to choose which mode they want.

merge.merge_entries: Prompt for file mode resolution vs assuming `EXEC`

---

tests/conftest.py
tests/dummy_editor.py
tests/test_fixup.py
tests/test_interactive.py

Previously, the test editor would always bind to port `8190`. However, this could cause problems if multiple tests are run in parallel on the same machine, or if that port is already bound by some other application.
This updates that fixture to bind to port `0`, which requests an unused port to be assigned by the OS. Then the `GIT_EDITOR` command uses whatever port was assigned.

test.edit: Bind to randomly-allocated port to avoid conflicts

---

gitrevise/odb.py
gitrevise/tui.py
gitrevise/utils.py
tests/test_cut.py

This allows root commits to be split with `git revise -c`.
This is related to and assists—but does not implement—#81 (_Add `--root` option_). Since `-c <commit>` refers to an actual targeted commit this was a bit easier as a first step. `-i <parent|--root>` refers to the possibly-non-existent parent, which requires a bit more special handling.

cut: Enable splitting root commits

---

CHANGELOG.md
docs/man.rst
gitrevise/merge.py
gitrevise/odb.py
gitrevise/todo.py
gitrevise/tui.py
gitrevise/utils.py
tests/test_cut.py
tests/test_interactive.py

Fixes #81 (_Add `--root` option_).
NOTE: This PR is based on/includes #96 (_cut: Enable splitting root commits_).
This adds the ability to run `git revise -i --root` to revise all commits down to the root commit.

interactive: Allow targeting `--root`

---

CHANGELOG.md
docs/man.rst
git-revise.1
gitrevise/odb.py
gitrevise/tui.py
tests/conftest.py
tests/test_gpgsign.py

This is #73 with review comments applied and two behavior changes.
(the broken Mac tests were https://github.com/pytest-dev/pytest/issues/5802)

Re-roll of GPG commit signing

---

tests/conftest.py
tests/test_cut.py
tests/test_fixup.py
tests/test_gpgsign.py
tests/test_interactive.py
tests/test_rerere.py
tests/test_reword.py
tox.ini

This enables `mypy` to run in `tests/`, and fixes a few minor nits surfaced by that.
Merge resolutions:
* The resolved merge of this branch + #116 (_test + pylint: enable pylint in tests/_) can be found at [rwe/git-revise@test-mypy-pylint](https://github.com/mystor/git-revise/compare/main...rwe:test-mypy-pylint?expand=1).
* The resolved  merge of this branch, #116 (_test + pylint…_) and #113 (_test.edit: Async editor_) can be found at [rwe/git-revise@test-mypy-pylint-async-editor](https://github.com/mystor/git-revise/compare/main...rwe:test-mypy-pylint-async-editor?expand=1).

test + mypy: enable mypy in tests/

---

gitrevise/merge.py
gitrevise/utils.py
pylintrc
tests/conftest.py
tests/dummy_editor.py
tests/test_cut.py
tests/test_fixup.py
tests/test_gpgsign.py
tests/test_interactive.py
tests/test_rerere.py
tests/test_reword.py
tox.ini

This enables `pylint` to be run in the `tests/` directory and fixes or suppresses the lint errors there.
NOTE: This _includes_ the following two minor PRs, which are split out for convenience:
Merging this PR would auto-close those ones; or they can be merged individually.
The remaining `not-context-manager` suppression would be resolved by the changes in #113 (_Async test editor_), but that change is not included here.
Merge resolutions:
* (*EDIT*: Now included here, since #117 is merged). ~The resolved merge of this branch + #117 (_test + mypy: enable mypy in tests/_) can be found at [rwe/git-revise@test-mypy-pylint](https://github.com/mystor/git-revise/compare/main...rwe:test-mypy-pylint?expand=1).~
* The resolved  merge of this branch, #117 (_test + mypy…_) and #113 (_test.edit: Async …

test + pylint: enable pylint in tests/

---

gitrevise/utils.py

When running pylint under py38:
> ```
> Value 'CompletedProcess' is unsubscriptable (unsubscriptable-object)
> ```
By quoting the annotation, pylint ignores it but mypy (which uses more recent `.pyi` information) respects it.
This was getting by CI because pylint is only run under Python 3.10 there.

py38: sh_run: `CompletedProcess[Any]` not recognized by pylint

---

tests/conftest.py
tests/test_gpgsign.py

`py.path` (via the `py` package) is deprecated and is not even a declared dependency; it's only available coincidentally through a transitive dependency on `tox` itself.
Its documentation recommends just using the standard pathlib.
From note here: https://github.com/mystor/git-revise/pull/94#discussion_r721637493

test: use `pathlib.Path` instead of deprecated `py.path`

---

gitrevise/odb.py
gitrevise/todo.py
gitrevise/utils.py
tests/test_rerere.py

Fixes a current CI failure. Alternatively,
lock black to the previous working version
(black==21.12b0).

Code: Reindent according to black==22.1.0

---

gitrevise/odb.py
gitrevise/tui.py
gitrevise/utils.py

This avoids buffering captured output that's always discarded. The parameter change from `nocapture` to `stdout` also makes it possible to direct that output to some other file/pipe.

odb.git: Send captured-but-discarded output to `DEVNULL`

---

tests/conftest.py
tests/test_cut.py
tests/test_fixup.py
tests/test_interactive.py
tests/test_rerere.py
tests/test_reword.py

This simplifies and fixes some race conditions in the editing server by introducing a blocking queue of pending edit requests.
This means that if the launched `git-revise` process invokes the editor before the test invokes `next_file()`, the request will still be picked up from the queue. Previously, this relied on checking an attribute `server.current` which was set in another thread.
This also splits apart `EditorFile` (the mutable/inspectable edit data that the test can manipulate) from the HTTP request handler itself. Beyond separation of those concerns, a side effect is that this fixes pylint's ability to disentangle the expected type of the `next_file` context manager. Previously the mutual modification between `Editor` and `EditorFile` previously forced it to give up. (Although …

test.edit: Async editor

---

gitrevise/merge.py
tests/test_rerere.py

When parsing conflicts, `git-rerere` ignores/preserves conflict markers that are not exactly the expected length, which defaults to 7.
For `<<<<<<< ` and `>>>>>>> `, it also requires them to end in a space, to avoid ambiguity.
See [`git/rerere.c`:`is_cmarker`](https://github.com/git/git/blob/cefe983a320c03d7843ac78e73bd513a27806845/rerere.c#L319) for reference + additional commentary.
This updates git-revise's parsing to treat them the same way.

rerere: Skip mismatched marker sizes like git-rerere does

---

gitrevise/odb.py
mypy.ini

This makes type checking PEP 484 compliant (as of 2018).
mypy will change its defaults soon.
See:
https://github.com/python/mypy/issues/9091
https://github.com/python/mypy/pull/13401

Use --no-implicit-optional for type checking

---

pylintrc
tests/conftest.py
tox.ini

This patch also more aggressively specifies versions for test-only
dependencies to avoid accidental CI failures due to mypy, pylint, or
black updating.

test: fix CI failures due to pylint changes

---

gitrevise/merge.py
gitrevise/utils.py
tests/test_fixup.py

This includes two minor commits to improve treatment of editor + paths, consistent with with `git-rebase` behaviour:
* The editor is launched from `cwd` rather than the arbitrary parent directory of a file. This means when editing `git-revise-todo`, for example, you can open/save/etc other local files rather than starting in a random temp dir. This is consistent with how the editor is launched for `git-rebase-todo`.
* When merging, file paths are shown as relative to the repo root, *not* relative to a phony filesystem root (`/`). In combination with the above, this means that the displayed path in diff/merge markers (e.g. `<<<<<<< file1 (new parent)`) are likely the correct path relative to the editor, making it easier to reference with typical "open file at this path" editor commands. …

edit: Run editor from cwd, not parent of file

---

.isort.cfg
docs/contributing.rst
gitrevise/merge.py
gitrevise/odb.py
gitrevise/todo.py
gitrevise/tui.py
gitrevise/utils.py
setup.py
tests/conftest.py
tests/test_cut.py
tests/test_fixup.py
tests/test_gpgsign.py
tests/test_interactive.py
tests/test_rerere.py
tests/test_reword.py
tox.ini

Note that `pylint` already depends on `isort`.
Using it makes import sorting unambiguous and automatic, which helps reduce cognitive load merging various branches in this codebase.
It was a little ambiguous whether it should be in the "lint" or "format" `tox` command, or another one altogether. It's included in "lint" here, because pylint already uses isort internally to catch coarse-grained "wrong-import-order" warnings.
This also updates the `contributing.rst` which referred to some incorrect tox commands.

lint: use `isort` to normalize import order

---

.github/workflows/test.yml
gitrevise/odb.py

In git 2.48, there is an issue where using `git update-ref` add a new entry to the reflog for a branch will cause corrupted reflog entries to be created for any symbolic refs referencing the updated reference. This impacts most usage of `git-revise`, as we update the default `HEAD` reference indirectly due to using `git rev-parse --symbolic-full-name` to resolve the identity of a branch.
This patch works around this issue in the common case by checking if the given name directly names a valid ref or symbolic ref, skipping the `--symbolic-full-name` resolution if it does. This means that HEAD will be directly updated by `git update-ref`, and receive valid reflog entries.
This workaround shouldn't negatively impact other git versions, and is largely an internal change to how symbolic refs …

Workaround reflog corruption bug in git 2.48

---

.github/dependabot.yml

This is a new feature that appeared after #141.

Use `uv` in dependabot config

---

gitrevise/utils.py
tests/test_cleanup_editor_content.py

Fix for https://github.com/mystor/git-revise/issues/108 and https://github.com/mystor/git-revise/issues/29
I'm not fluent in Python so let me know about any stupid mistakes.
Each commit is atomic so the easiest way to review this PR is commit-by-commit.
Co-authored-by: @RuRo

Add support for `git config commit.cleanup` & `git config commit.verbose`
